#!/usr/bin/groovy

library 'aosp-pipeline'

withEnv([ "NODE_LABEL=<node-label>",
          "JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64" ]) {
    aospPipeline {
        manifestUrl     = '<https://github.com/PixelExperience/manifest>'
        repoBranch      = '<thirteen>'
        targetProduct   = 'aosp_ginkgo'
        buildVariant    = 'eng'
        ccacheEnabled   = true
        ccacheSize      = '50G'
        jobCpus         = 12
        logcatEnabled   = true
        emulatorEnabled = true
        emulatorOpts    = [
            "-memory 33949",
            "-accel on",
            "-no-snapshot",
            "-timezone Europe/Paris"
        ]
        ctsTests        = [ "<test_1>", "<test_2>" ]
        skipStages      = skip
        mailTo          = "<firstname.lastname@domain.com>"
    }
}
